In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import time
import multiprocessing

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from collections import Counter
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.ensemble import AdaBoostClassifier


from imblearn.over_sampling import SMOTE, ADASYN
from sklearn.metrics import confusion_matrix, r2_score, mean_squared_error
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report, precision_recall_curve


In [12]:
df = pd.read_csv('Train_Data.csv')
df.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

    attack  
0  neptune  
1   normal  
2   normal  
3   normal  
4  neptune  

[5 rows x 43 columns]

In [13]:
df.shape

(86845, 43)

In [14]:
df.replace({'normal': 0, 'neptune': 1}, inplace=True)
df.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [15]:
le = LabelEncoder()
df['protocoltype'] = le.fit_transform(df['protocoltype'])
df['service'] = le.fit_transform(df['service'])
df['flag'] = le.fit_transform(df['flag'])

In [16]:
df.head()

duration  protocoltype  service  flag  srcbytes  dstbytes  land  \
0         0             1       33     1         0         0     0   
1         0             1       49     8      1239       400     0   
2         0             1       22     8       222       945     0   
3         0             1       22     8       235      1380     0   
4         0             1       62     1         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [17]:
X=df.drop(['attack'],axis=1)
y=df['attack']

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [21]:
def score(model, title = "Default"):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    print(confusion_matrix(y_test, preds))
    accuracy = round(accuracy_score(y_test, preds), 5)
    print('Accuracy for', title, ':', accuracy, '\n')

In [22]:
lg = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
score(lg, "Logistic Regression")

[[17770     8]
 [    9 10872]]
Accuracy for Logistic Regression : 0.99941 



D:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
adb = AdaBoostClassifier(n_estimators=1000, random_state=0)
score(adb, "AdaBoost Classifier")

[[17778     0]
 [    1 10880]]
Accuracy for AdaBoost Classifier : 0.99997 



In [26]:
rf = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0)
score(rf, "Random Forest Classifier")

[[17777     1]
 [    0 10881]]
Accuracy for Random Forest Classifier : 0.99997 



In [27]:
knn = KNeighborsClassifier()
score(knn, "KNeighborsClassifier")

[[17748    30]
 [    8 10873]]
Accuracy for KNeighborsClassifier : 0.99867 



In [28]:
dt = DecisionTreeClassifier()
score(dt, "DecisionTreeClassifier")

[[17772     6]
 [    9 10872]]
Accuracy for DecisionTreeClassifier : 0.99948 



In [29]:
xgb = XGBClassifier(n_estimator=1000, learning_rate=0.01)
score(xgb, "XGBClassifier with n_estimators=1000 and learning_rate=0.01")

[17:14:21] WARNING: C:\Users\dev-admin\croot2\xgboost-split_1675461376218\work\src\learner.cc:767: 
Parameters: { "n_estimator" } are not used.

[[17773     5]
 [   12 10869]]
Accuracy for XGBClassifier with n_estimators=1000 and learning_rate=0.01 : 0.99941 



In [30]:
svm_model = SVC(kernel='rbf', random_state=42)
score(svm_model, "SVM")

[[17778     0]
 [10881     0]]
Accuracy for SVM : 0.62033 

